### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Agrim-Sharma174** [collab-community/become-a-member#13]
### Name

Agrim Sharma

### Discord Username (if applicable)

AGRIM SHARMA#8545

### Twiiter username (if applicable)

@Agrim_Sharma174

### Additional Context

I am a moderator (Graphics Manager)

**Comment by KendallDoesCoding** [comment]
@Agrim-Sharma174 - Please wait for a day as GitHub has restricted us from sending invites, as we have send 50+ invites today itself, sorry for the inconvenience. In the meanwhile, you can create your journey in [Journey Book](https://github.com/collab-community/journey-book)

**Comment by Adarsh-jaiss** [comment]
-- Hey agrim, kindly checkout your email. 
-- We have sent you an invitation

**Comment by Agrim-Sharma174** [comment]
Done.
