### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by harshu0111** [collab-community/become-a-member#19]
### Name

HARSHIT MISHRA 

### Discord Username (if applicable)

harshit__mishra#2344

### Twiiter username (if applicable)

itsharshit01

### Additional Context

I'm very excited to join this community to learn and contribute as well .

**Comment by KendallDoesCoding** [comment]
Please wait for a day as GitHub has restricted us from sending invites, as we have send 50+ invites today itself, sorry for the inconvenience. In the meanwhile, you can create your journey in [Journey Book](https://github.com/collab-community/journey-book)

**Comment by Adarsh-jaiss** [comment]
-- Hey harshit, we have sent you an invitation
-- kindly check it out 
-- We are happy to onboard you in our community 😄
