### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by sanjaymenaria03** [collab-community/become-a-member#20]
### Name

Sanjay Menaria

### Discord Username (if applicable)

Sanjay#2862

### Twiiter username (if applicable)

@SanjayM67502055

**Comment by KendallDoesCoding** [comment]
Please wait for a day as GitHub has restricted us from sending invites, as we have send 50+ invites today itself, sorry for the inconvenience. In the meanwhile, you can create your journey in [Journey Book](https://github.com/collab-community/journey-book)

**Comment by Adarsh-jaiss** [comment]
-- Hey Sanajy , we have sent you an invitation
-- kindly check it out
-- We are happy to onboard you in our community 😄
