### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by TheOjasSingh** [collab-community/become-a-member#21]
### Name

Ojas Singh

### Discord Username (if applicable)

Ojas#7820

### Twiiter username (if applicable)

_Singh_Ojas

### Additional Context

Found about the collab community on twitter. And hoping to meet and collab with new and awesome developers from across world.

**Comment by KendallDoesCoding** [comment]
Please wait for a day as GitHub has restricted us from sending invites, as we have send 50+ invites today itself, sorry for the inconvenience. In the meanwhile, you can create your journey in [Journey Book](https://github.com/collab-community/journey-book)

**Comment by Adarsh-jaiss** [comment]
-- Hey ojas , we have sent you an invitation
-- kindly check it out
-- We are happy to onboard you in our community 😄
