### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by RagulSankar04** [collab-community/become-a-member#22]
### Name

Ragul Sankar

### Discord Username (if applicable)

iam_ragul#2620

### Twiiter username (if applicable)

_ragul_sankar_

### Additional Context

I got to know about this from twitter and I would like yo improve my leadership and communication skills

**Comment by KendallDoesCoding** [comment]
Please wait for a day as GitHub has restricted us from sending invites, as we have send 50+ invites today itself, sorry for the inconvenience. In the meanwhile, you can create your journey in [Journey Book](https://github.com/collab-community/journey-book)

**Comment by Adarsh-jaiss** [comment]
-- Hey Rahul , we have sent you an invitation
-- kindly check it out
-- We are happy to onboard you in our community 😄
