### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by MaryAyobami** [collab-community/become-a-member#23]
### Name

Mary Ogunmola 

### Discord Username (if applicable)

MaryAyobami 

### Twiiter username (if applicable)

@blessedwithjoy_

**Comment by KendallDoesCoding** [comment]
Please wait for a day as GitHub has restricted us from sending invites, as we have send 50+ invites today itself, sorry for the inconvenience. In the meanwhile, you can create your journey in [Journey Book](https://github.com/collab-community/journey-book)

**Comment by Adarsh-jaiss** [comment]
-- Hey Mary , we have sent you an invitation
-- kindly check it out
-- We are happy to onboard you in our community 😄
