### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Ebukachuqz** [collab-community/become-a-member#24]
### Name

Ebuka

### Discord Username (if applicable)

Ebuka#2566

### Twiiter username (if applicable)

ebukachuqz

### Additional Context

I learnt about Collab Community from Adarsh's tweet. 
I would love to join this community to connect with other people, make new friends, do more opensource and improve my skill.

**Comment by KendallDoesCoding** [comment]
Please wait for a day as GitHub has restricted us from sending invites, as we have send 50+ invites today itself, sorry for the inconvenience. In the meanwhile, you can create your journey in [Journey Book](https://github.com/collab-community/journey-book)

**Comment by Ebukachuqz** [comment]
Will do

**Comment by Adarsh-jaiss** [comment]
-- Hey Ebuka ,  we have sent you an invitation
-- kindly check it out
-- We are happy to onboard you in our community 😄
