### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by codingkush** [collab-community/become-a-member#29]
### Name

Kush Gupta 

### Discord Username (if applicable)

Kush#4965

### Twiiter username (if applicable)

mekushgupta

### Additional Context

Hello everyone. My name is Kush Gupta  and I'm from Kanpur ,Uttar Pradesh ,India . I have completed bachelor of computer application from  virendra swarup college of management studies ,Kanpur. 

I am a Computer Science student . I very please to exchange ideas in computer  and other field with different peoples.

I am interested in computer science and topics like Artificial Intelligence have always had a fascination for me.

**Comment by KendallDoesCoding** [comment]
Hey Kush, 

welcome to our community, please accept the invite
