### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by 0xCUB3** [collab-community/become-a-member#47]
### Name

Alexander (0xCUBE)

### Discord Username (if applicable)

0xCUBE#0001

### Twiiter username (if applicable)

0xCU8E

### Additional Context

Hello everyone!
I'm Alex from the USA. I'm a student and love to code and tinker with tech. I am an aspiring computer science major and love playing with website building, homelabs, and server management/sysadmin. I also love contributing to open-source projects and have made a few of my own! I would love to be a part of the collab community to be a part of something that's bigger than myself, to which I can (hopefully 😊) contribute a lot. 
Thanks for considering me!

**Comment by 0xCUB3** [comment]
just a note - my discord username discrim (the 4 numbers) might change soon because my nitro will expire. Just wanted to put it out there. The new username will be in my github account when it does happen.

**Comment by KendallDoesCoding** [comment]
> just a note - my discord username discrim (the 4 numbers) might change soon because my nitro will expire. Just wanted to put it out there. The new username will be in my github account when it does happen.

No worries! We don't require the Discord username as a matter of fact, but I see you've joined the server so that's great!
