### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by sambhavgupta0705** [collab-community/become-a-member#6]
### Name

Sambhav Gupta

### Discord Username (if applicable)

Sam07#7309

**Comment by sambhavgupta0705** [comment]
hi

**Comment by KendallDoesCoding** [comment]
Hi, I already sent you the invite earlier in the day, and I see that you have joined the organization! Request you to please make the visiblity of this organization on your profile "public". you can do it on https://github.com/orgs/collab-community/people :)

**Comment by Adarsh-jaiss** [comment]
-- https://discord.gg/PGadh3Vyuv
-- join our discrod community via above links
-- Connect with me on Twitter @twtadarsh
-- and do follow @collab__ on Twitter
