### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by hemantwasthere** [collab-community/become-a-member#63]
### Name

Hemant

### Discord Username (if applicable)

hemantwasthere

### Twiiter username (if applicable)

hemantwasthere

### Additional Context

Hello, I want to join this awesome community

**Comment by hemantwasthere** [comment]
@Adarsh-jaiss Hello can you please close the issue : )

**Comment by Adarsh-jaiss** [comment]
-- i have sent you invitation link :) 
Kindly check your email
