### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [collab-community/become-a-member#64]
### Name

Sulagna Dutta Roy

### Discord Username (if applicable)

Sulagna Dutta Roy #2627

### Twiiter username (if applicable)

@SulagnaDuttaRo1

### Additional Context

Hi, I want to learn from this community and help people through the knowledge. Thank you

**Comment by Adarsh-jaiss** [comment]
-- i have sent you invitation link :) 
Kindly check your email
