### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by GyaneshSamanta** [collab-community/become-a-member#7]
### Name

Gyanesh Samanta

### Discord Username (if applicable)

Gyanesh Samanta#1723

**Comment by KendallDoesCoding** [comment]
I sent you a invite just now, please accept it and make the organization visible on your profile at https://github.com/orgs/collab-community/people when done!

**Comment by Adarsh-jaiss** [comment]
-- Add your GitHub username

**Comment by GyaneshSamanta** [comment]
Hey I still haven't received an invite, can you please check up?

**Comment by KendallDoesCoding** [comment]
Please create a new issue and try again. Will send in manually when I get
to my laptop

**Comment by KendallDoesCoding** [comment]
Hi, you were invited that day itself, please accept it from: https://github.com/collab-community if you did not get a notif/email notif
