### ISSUE TITLE
Invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by aryav-v** [collab-community/become-a-member#9]
### Name

Aryav Chaturvedi

### Discord Username (if applicable)

Aryav#1854

### Twiiter username (if applicable)

aryav_v

### Additional Context

Found collab-community on Twitter , looking forward to contribute towards the community  :)

**Comment by KendallDoesCoding** [comment]
Hi, I sent you a invite just now, please accept it and make the organization visible on your profile at https://github.com/orgs/collab-community/people when done!
